### PR TITLE
Updates on plotting routines and coordinate transforms to openPMD and OPAL

### PR DESCRIPTION
**Pull request by jp-ga**
- added functionality to `plot_projections`
- added OPAL-to-bmadx coordinate transformation in `pmd_utils`
- added more openPMD-to-bmadx transformations in `pmd_utils`
- renamed beam generator to `distgen_utils`

### CODE REVIEW

**Comment by jp-ga** [comment]
@roussel-ryan

**Review by roussel-ryan — COMMENTED** [review]
I would rename any variables/functions named `par` to `particle` if possible to make code more readable for outside users

**Comment by ChristopherMayes** [comment]
I recommend leaving conversions from OPAL and other codes to the ParticleGroup object, and keep Bmad-X clean. So, in Bmad-X there should be its internal particle structures, and openPMD-beamphysics.

**Comment by jp-ga** [comment]
@ChristopherMayes I agree, but I didn't find any OPAL reader in openPMD-beamphysics

**Comment by ChristopherMayes** [comment]
The HDF5 OPAL reader `opal_to_data(h5)` is in https://github.com/ChristopherMayes/openPMD-beamphysics/blob/master/pmd_beamphysics/interfaces/opal.py

If you need an ASCII reader, we could add that with another function `opal_ascii_to_data(filePath)`. 

The basic idea, is that the function makes a dict of data that a ParticleGroup can be initialized on. 

Better to do it in a common place, where more people see it and bugs/subtleties can be handled.

**Comment by ChristopherMayes** [comment]
We could add a reader there

**Comment by jp-ga** [comment]
I see, thanks. The OPAL coordinates were given to me as an ASCII file instead of an h5 file. I will ask for the h5 file. For now, I will leave this PR open and work in my dev branch.

**Comment by ChristopherMayes** [comment]
Well if you have time, make a PR to openPMD-beamphysics adding a `opal_ascii_to_data(filePath)`.

**Comment by jp-ga** [comment]
Will include OPAL-openPMD coordinate transforms in openPMD-Beamphysics

**Pull request closed without merging**
