### PR TITLE
Bmad-X version 0.0.1

### PR DESCRIPTION
**Pull request by jp-ga**
First version of Bmad-X

### CODE REVIEW

**Comment by ChristopherMayes** [comment]
@jp-ga You have a lot of temporary files checked in, like the `digested` files from Bmad, and some `.nfs` files. Could you remove them, and carefully look at what files are actually being added?

**Comment by jp-ga** [comment]
@ChristopherMayes Done!

**Comment by ChristopherMayes** [comment]
@jp-ga this still has `__pycache__` directories

**Comment by jp-ga** [comment]
@ChristopherMayes done!

**Comment by ChristopherMayes** [comment]
@jp-ga Looks good!

**Pull request merged**
