### PR TITLE
fix open pmd transform and include beam generator

### PR DESCRIPTION
**Pull request by jp-ga**

### CODE REVIEW

**Comment by jp-ga** [comment]
@roussel-ryan

**Comment by roussel-ryan** [comment]
In the environment file: instead of installing torch via pip, you can add the pytorch channel and install torch using conda

**Comment by jp-ga** [comment]
@roussel-ryan  done

**Comment by roussel-ryan** [comment]
I would suggest a flag in `plot_projections` that allows the user to force all of the 2d phase space plots (and x-axes of histograms) to have the same limits, also have the function return the figure for further processing/customization/saving etc

**Comment by jp-ga** [comment]
@roussel-ryan  done!

**Review by roussel-ryan — APPROVED** [review]

**Pull request merged**
